# Generated by Django 5.0.4 on 2024-04-13 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VitalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respiration_rate', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('pulse', models.FloatField()),
                ('systol', models.FloatField()),
                ('diastol', models.FloatField()),
                ('ews_score', models.FloatField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBackend.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CentileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_percentile', models.FloatField()),
                ('fifth_percentile', models.FloatField()),
                ('tenth_percentile', models.FloatField()),
                ('ninetieth_percentile', models.FloatField()),
                ('ninetyfifth_percentile', models.FloatField()),
                ('ninetyninth_percentile', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vital_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBackend.vitalmodel')),
            ],
        ),
    ]
