# Generated by Django 5.0.4 on 2024-06-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBackend', '0005_alter_vitaldata_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=255),
        ),
        migrations.AddField(
            model_name='vitaldata',
            name='temperature',
            field=models.FloatField(default=32),
        ),
    ]
