# Generated by Django 5.0.4 on 2024-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBackend', '0006_patient_gender_vitaldata_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vitaldata',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
